n = input('Digite alguma coisa: ')
print('O tipo primitivo dessa sentença é: ', type(n))
print('Só tem espaços? ', n.isspace())
print('É um número? ', n.isnumeric())
print('É alfabético? ', n.isalpha())
print('É alfanumérico? ', n.isalnum())
print('Está em maiúsculas? ', n.isupper())
print('Está em minúsculas? ', n.islower())
print('Está em código ascii? ', n.isascii())
print('É um digíto? ', n.isdecimal())
print('Está capitalizada? ', n.istitle())
